Feat: run postman test in ci with debug build artifact

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -124,34 +124,55 @@ jobs:
         with:
           command: test
 
-      # - name: Run API with Cargo
-      #   run: cargo run &
+  postman_test:
+    name: Run Postman Tests
+    runs-on: ubuntu-latest
+    needs: unit_test
 
-      # - name: Install Node.js
-      #   uses: actions/setup-node@v2
-      #   with:
-      #     node-version: '18'
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4.2.2
 
-      # - name: Install Newman
-      #   run: npm install -g newman
+      - name: Setup Rust
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          override: true
 
-      # - name: Retrieve and Run Postman Collection
-      #   env:
-      #     POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
-      #     POSTMAN_CORE_API_COLLECTION_ID: ${{ secrets.POSTMAN_CORE_API_COLLECTION_ID }}
-      #   run: |
-      #     curl -X GET "https://api.getpostman.com/collections/$POSTMAN_CORE_API_COLLECTION_ID" \
-      #       -H "X-Api-Key: $POSTMAN_API_KEY" \
-      #       -o collection.json
+      - name: Download Dependency Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: rust-build-debug
+          path: target/debug/
 
-      #     # Check if the curl command was successful
-      #     if [ $? -eq 0 ]; then
-      #       echo "The collection was successfully retrieved and saved to collection.json"
+      - name: Run API with Cargo
+        run: cargo run &
 
-      #       # Run the collection with Newman
-      #       newman run collection.json
-      #     else
-      #       echo "An error occurred while retrieving the collection"
-      #       exit 1
-      #     fi
+      - name: Install Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '18'
+
+      - name: Install Newman
+        run: npm install -g newman
+
+      - name: Retrieve and Run Postman Collection
+        env:
+          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
+          POSTMAN_CORE_API_COLLECTION_ID: ${{ secrets.POSTMAN_CORE_API_COLLECTION_ID }}
+        run: |
+          curl -X GET "https://api.getpostman.com/collections/$POSTMAN_CORE_API_COLLECTION_ID" \
+            -H "X-Api-Key: $POSTMAN_API_KEY" \
+            -o collection.json
+
+          # Check if the curl command was successful
+          if [ $? -eq 0 ]; then
+            echo "The collection was successfully retrieved and saved to collection.json"
+
+            # Run the collection with Newman
+            newman run collection.json
+          else
+            echo "An error occurred while retrieving the collection"
+            exit 1
+          fi
 
