Feat: add postman test in the ci

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -77,7 +77,7 @@ jobs:
           args: --release
 
   test:
-    name: Run Tests
+    name: Run API and Postman Tests
     runs-on: ubuntu-latest
     needs: build
 
@@ -91,8 +91,40 @@ jobs:
           toolchain: stable
           override: true
 
-      - name: Run Tests
+      - name: Run Rust Tests
         uses: actions-rs/cargo@v1
         with:
           command: test
+
+      - name: Run API with Cargo
+        run: cargo run &
+        working-directory: ./your_rust_project_directory
+
+      - name: Install Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '14'
+
+      - name: Install Newman
+        run: npm install -g newman
+
+      - name: Retrieve and Run Postman Collection
+        env:
+          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
+          POSTMAN_CORE_API_COLLECTION_ID: ${{ secrets.POSTMAN_CORE_API_COLLECTION_ID }}
+        run: |
+          curl -X GET "https://api.getpostman.com/collections/$POSTMAN_CORE_API_COLLECTION_ID" \
+            -H "X-Api-Key: $POSTMAN_API_KEY" \
+            -o collection.json
+
+          # Check if the curl command was successful
+          if [ $? -eq 0 ]; then
+            echo "The collection was successfully retrieved and saved to collection.json"
+
+            # Run the collection with Newman
+            newman run collection.json
+          else
+            echo "An error occurred while retrieving the collection"
+            exit 1
+          fi
 
