Feat: run tests with debug artifact

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -98,54 +98,60 @@ jobs:
           name: rust-build-release
           path: target/release/
 
-  # test:
-  #   name: Run API and Postman Tests
-  #   runs-on: ubuntu-latest
-  #   needs: build
+  unit_test:
+    name: Run Unit Tests
+    runs-on: ubuntu-latest
+    needs: build
 
-  #   steps:
-  #     - name: Checkout Repository
-  #       uses: actions/checkout@v4.2.2
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4.2.2
 
-  #     - name: Setup Rust
-  #       uses: actions-rs/toolchain@v1
-  #       with:
-  #         toolchain: stable
-  #         override: true
+      - name: Setup Rust
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          override: true
 
-  #     - name: Run Rust Tests
-  #       uses: actions-rs/cargo@v1
-  #       with:
-  #         command: test
+      - name: Download Debug Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: rust-build-debug
+          path: target/debug/
 
-  #     - name: Run API with Cargo
-  #       run: cargo run &
+      - name: Run Rust Tests
+        uses: actions-rs/cargo@v1
+        with:
+          command: test
 
-  #     - name: Install Node.js
-  #       uses: actions/setup-node@v2
-  #       with:
-  #         node-version: '18'
+      # - name: Run API with Cargo
+      #   run: cargo run &
 
-  #     - name: Install Newman
-  #       run: npm install -g newman
+      # - name: Install Node.js
+      #   uses: actions/setup-node@v2
+      #   with:
+      #     node-version: '18'
 
-  #     - name: Retrieve and Run Postman Collection
-  #       env:
-  #         POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
-  #         POSTMAN_CORE_API_COLLECTION_ID: ${{ secrets.POSTMAN_CORE_API_COLLECTION_ID }}
-  #       run: |
-  #         curl -X GET "https://api.getpostman.com/collections/$POSTMAN_CORE_API_COLLECTION_ID" \
-  #           -H "X-Api-Key: $POSTMAN_API_KEY" \
-  #           -o collection.json
+      # - name: Install Newman
+      #   run: npm install -g newman
 
-  #         # Check if the curl command was successful
-  #         if [ $? -eq 0 ]; then
-  #           echo "The collection was successfully retrieved and saved to collection.json"
+      # - name: Retrieve and Run Postman Collection
+      #   env:
+      #     POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
+      #     POSTMAN_CORE_API_COLLECTION_ID: ${{ secrets.POSTMAN_CORE_API_COLLECTION_ID }}
+      #   run: |
+      #     curl -X GET "https://api.getpostman.com/collections/$POSTMAN_CORE_API_COLLECTION_ID" \
+      #       -H "X-Api-Key: $POSTMAN_API_KEY" \
+      #       -o collection.json
 
-  #           # Run the collection with Newman
-  #           newman run collection.json
-  #         else
-  #           echo "An error occurred while retrieving the collection"
-  #           exit 1
-  #         fi
+      #     # Check if the curl command was successful
+      #     if [ $? -eq 0 ]; then
+      #       echo "The collection was successfully retrieved and saved to collection.json"
+
+      #       # Run the collection with Newman
+      #       newman run collection.json
+      #     else
+      #       echo "An error occurred while retrieving the collection"
+      #       exit 1
+      #     fi
 
